name: studhunt CI/CD

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build result
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: dist

      - name: Delete previous bundle
        uses: appleboy/ssh-action@master
        with:
          host: 95.163.212.36
          username: ubuntu
          key: ${{ secrets.APP_SECRET_TO_VM_UBUNTU }}
          script: rm -rf /frontend/2020_2_MVVM/dist/

      - name: Transfer build files to server
        uses: appleboy/scp-action@v0.0.10
        with:
          host: 95.163.212.36
          username: ubuntu
          key: ${{ secrets.APP_SECRET_TO_VM_UBUNTU }}
          source: "dist/*"
          target: "/home/ubuntu/frontend/2020_2_MVVM"